name: 'YAMLValidation'
on:
  push:
    branches:
      - main
      - Prod
      - Test
    paths:
      - '**.yml'
      - '**.yaml'
  pull_request:
    branches:
      - main
      - Prod
      - Test
    paths:
      - '**.yml'
      - '**.yaml'
permissions:
  contents: read
  pull-requests: write
jobs:
  my_first_job:
    name: yaml-validatior
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: json-yaml-validate
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v3.2.1
